name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Remove files you do NOT want to deploy
      - name: Remove unused files
        run: |
          rm -f docker-compose.yml

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: "face-attendance"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
